name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.0.5, 1.2.0, 1.3]
        julia-arch: [x64, x86]
        os: [ubuntu-latest, macOS-latest]
        exclude:
          - os: macOS-latest
            julia-arch: x86

    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-runtest@master
      - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v1.0.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}